Zeus w caam review
bgnetworks/meta-bgn-essa pull request #2
Opened 2021-11-12 19:04 UTC by lee19830115

adjust image sizes; add BG network logo; set boot mode to emmc

2021-11-13 00:20 UTC, rlysecky reviewed
This guide looks great. There are few formatting inconsistencies with capitalization that would be good to update. I left a comment for the first one I noticed.

2021-11-13 00:20 UTC, rlysecky commented on docs/Quick_Start_Guide.md
>  The files and directories that are in the bgn-essa-c444
```suggestion
Files and directories that are in the `bgn-essa-c444`:
```

2021-11-13 00:20 UTC, rlysecky commented on docs/Quick_Start_Guide.md
>  The Yocto meta directories that are in the sources
```suggestion
Yocto meta directories that are in `sources`:
```

2021-11-13 00:20 UTC, rlysecky commented on docs/Quick_Start_Guide.md
>  #### 4. setup the build environment at first time
I think we should start each numbered step with a capital letter.

2021-11-13 00:20 UTC, rlysecky commented on docs/Quick_Start_Guide.md
>  **Note**: _the image build may take a few hours at the first time_
```suggestion
**Note**: _The initial image build may take a few hours_
```

2021-11-16 04:44 UTC, danie007 requested changes
Over all nice work 👌, some minor changes can be made, if make sense!

---

CC @tkmozhi

2021-11-16 04:44 UTC, danie007 commented on docs/Quick_Start_Guide.md
> +dmsetup -v create myEncryptedBlock --table "0 $(blockdev --getsz /dev/loop0) crypt capi:tk(cbc(aes))-plain :36:logon:mykey2: 0 /dev/loop0 0 1 sector_size:512"
Nice catch and kudos for updating the `dmsetup` commands 👍

2021-11-16 04:44 UTC, danie007 commented on meta-mender-c444/templates/local.conf.append
>  # Uncomment the following 2 lines to boot from eMMC on imx8mq-itx-p-c444
Updating the boot medium to internal eMMC is a good idea 💡 . But can we update the `comment` as well?
```suggestion
# Boot from eMMC
```

2021-11-16 04:44 UTC, danie007 commented on meta-mender-c444/templates/local.conf.append
>  # Boot from SD
```suggestion
# Uncomment the following 2 lines to boot from SD Card on imx8mq-itx-p-c444
```

2021-11-16 22:04 UTC, lee19830115 commented on meta-mender-c444/templates/local.conf.append
>  # Uncomment the following 2 lines to boot from eMMC on imx8mq-itx-p-c444
look nice. maybe we reword the comments in this way?

SD and eMMC boot are mutually exclusive. Please select only one, either SD boot or eMMC boot

Boot from eMMC
Uncomment the following 2 lines to boot from eMMC on imx8mq-itx-p-c444


Boot from SD card
Uncomment the following line to boot from a SD card on imx8mq-itx-p-c444

2021-11-18 02:58 UTC, danie007 commented on meta-mender-c444/templates/local.conf.append
>  # Uncomment the following 2 lines to boot from eMMC on imx8mq-itx-p-c444
eMMC is already in effect (_i.e., uncommented_). Hence the following comment/line shall be removed 

```suggestion
```

—-

CC @tkmozhi

2021-11-18 03:54 UTC, danie007 approved these changes
LGTM 👍

2021-11-18 04:17 UTC, merged